CREATE DATABASE IF NOT EXISTS CAPSTONE_TWO_DB;

USE DATABASE CAPSTONE_TWO_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MART;

USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_USERS (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_PRODUCTS (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_CARTS (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_POSTS (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_COMMENTS (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_QUOTES (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_RECIPES (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_CATEGORIES (
    RAW_DATA VARIANT
);


SELECT *
FROM RAW_USERS;

SELECT
    RAW_DATA:users[0].firstName AS FIRST_NAME,
    RAW_DATA:users[0].lastName AS LAST_NAME,
    RAW_DATA:users[0].email AS EMAIL
FROM RAW_USERS;

SELECT

    u.first_name,
    u.last_name,
    p.product_name,
    fps.quantity,
    fps.gross_sales

FROM MART.FACT_PRODUCT_SALES fps

JOIN MART.DIM_USERS u
ON fps.user_id = u.user_id

JOIN MART.DIM_PRODUCTS p
ON fps.product_id = p.product_id;

CREATE SCHEMA IF NOT EXISTS REPORTING;

SHOW TABLES;