version: 2

models:

  - name: stg_users

    columns:

      - name: user_id
        tests:
          - unique
          - not_null

      - name: email
        tests:
          - unique
          - not_null

  - name: stg_products

    columns:

      - name: product_id
        tests:
          - unique
          - not_null

      - name: product_name
        tests:
          - not_null
          
  - name: stg_carts

    columns:

      - name: cart_id
        tests:
          - unique
          - not_null

      - name: user_id
        tests:
          - not_null

  - name: stg_posts

    columns:

      - name: post_id
        tests:
          - unique
          - not_null

      - name: user_id
        tests:
          - not_null

      - name: title
        tests:
          - not_null

      - name: body
        tests:
          - not_null

      - name: views
        tests:
          - not_null

  - name: stg_comments

    columns:

      - name: comment_id
        tests:
          - unique
          - not_null

      - name: comment
        tests:
          - not_null

      - name: post_id
        tests:
          - not_null

      - name: user_id
        tests:
          - not_null

      - name: username
        tests:
          - not_null

  - name: stg_quotes
    columns:
      - name: quote_id
        tests:
          - unique
          - not_null
      - name: quote
        tests:
          - not_null
      - name: author
        tests:
          - not_null

  - name: stg_recipes
    columns:
      - name: recipe_id
        tests:
          - unique
          - not_null
      - name: recipe_name
        tests:
          - not_null
      - name: instructions
        tests:
          - not_null

  - name: stg_categories
    columns:
      - name: category_name
        tests:
          - not_null
      - name: category_slug
        tests:
          - unique
          - not_null
      - name: category_url
        tests:
          - not_null